MedicineMonitoring/MedicineMonitoring/Models/Medicine.cs
using MedicineMonitoring.ModelValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MedicineMonitoring.Models
{
    public class Medicine
    {
        [Key]
        public int MedId { get; set; }

        [Required(ErrorMessage = " Medicine Name is Required")]
        [Display(Name = "Medicine Name")]
        [RegularExpression("^[a-zA-Z|0-9 ]*$", ErrorMessage = "Only Alphabets and Numbers are allowed.")]
        public string MedName { get; set; }



        [Required(ErrorMessage = " Manufacturer Name is Required")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only Alphabets are allowed.")]
        [Display(Name = "Manufacturer")]
        public string Manufacturer { get; set; }

        [Required(ErrorMessage = "Disease/illness Details are Required")]
        [Display(Name = "Disease/illness")]
        [RegularExpression("^[a-zA-Z, ]*$", ErrorMessage = "Only Alphabets are allowed.")]
        public string Disease { get; set; }

        [Required(ErrorMessage = "Please Provide Branch Name")]
        [Display(Name = "Branches")]
        public string BranchAvaliable { get; set; }

        [Required(ErrorMessage = "Please Provide Address")]
        [Display(Name = "City")]
        public string Address { get; set; }

        [ManufucturingDate]
        [Required(ErrorMessage = " Manufacture Date is Required")]
        [Display(Name = "Manufacturing Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ManufactureDate { get; set; }

        [ExperidateValidation]
        [Required(ErrorMessage = " Expiry Date is Required")]
        [Display(Name = "Expiry Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ExpiryDate { get; set; }



        [Required(ErrorMessage = "Cost is required.")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed.")]
        [Display(Name = "Cost")]

        public float cost { get; set; }


        [Required(ErrorMessage = "Quantity is required.")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed.")]
        [Display(Name = "Quantity")]
        public int quantity { get; set; }

        public Nullable<DateTime> CreatedDate { get; set; }

        public Nullable<DateTime> IsEditedDate { get; set; }
    }
}

MedicineMonitoring/MedicineMonitoring/Controllers/MedicineController.cs
using MedicineMonitoring.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MedicineMonitoring.Controllers
{
    
    public class MedicineController : Controller
    {
        MedicineMonitoring.Methods.Methods methods = new MedicineMonitoring.Methods.Methods();
        // GET: Medicine
        MedicineDBContext _dbcontext = new MedicineDBContext();
        //List of All Medicine Viewed By Admin
        [Authorize(Roles = "Admin")]
        public ActionResult MedList()
        {
            if (_dbcontext.Medicines.ToList().Count == 0)
            {
                ViewBag.msg = 1;
                return View();
            }
            else
            {
                return View(_dbcontext.Medicines.ToList());
            }
        }
        //Adding Medicine to list By Admin and Branch Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult AddMedicine()
        {
            ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
            ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
            Medicine medicine = new Medicine();
            return View(medicine);
        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult AddMedicine(Medicine medicine)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
                return View();
            }
            else
            {
               
                HttpCookie authCookie = HttpContext.Request.Cookies[FormsAuthentication.FormsCookieName];
                FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
                User user = _dbcontext.Users.FirstOrDefault(y => y.UserId == authTicket.Name);
                var branch = _dbcontext.Branches.FirstOrDefault(x => x.BranchName == medicine.BranchAvaliable && x.BranchAddress == medicine.Address&&x.BranchId==user.BranchId);

                if (branch != null||user.Usercategory==(UserCategory)1)
                {
                    medicine.CreatedDate = DateTime.UtcNow;
                    _dbcontext.Medicines.Add(medicine);
                    methods.Save(_dbcontext);
                    ViewBag.Message = "Medicine Details Added Succesfully";
                    return View();
                }
                else
                {
                    ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                    ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
                   
                    ModelState.AddModelError("", "City is Mismatch with Branch");
                    return View();
                }
            }
        
        }
        //Details of Medicine Viewed By both Branch Admin and Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();
                return View(medicine);
            }

            return View();

        }
        //Editing details of medicine by both Branch Admin and Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult Edit(int? id)
        {
            Medicine medicine = null;
            if (id != null)
            {
                ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
                medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();

            }

            return View(medicine);

        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult Edit(Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                HttpCookie authCookie = HttpContext.Request.Cookies[FormsAuthentication.FormsCookieName];
                FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
                User user = _dbcontext.Users.FirstOrDefault(y => y.UserId == authTicket.Name);
                var branch = _dbcontext.Branches.FirstOrDefault(x => x.BranchName == medicine.BranchAvaliable && x.BranchAddress == medicine.Address && x.BranchId == user.BranchId);

                if (branch != null|| user.Usercategory == (UserCategory)1)
                {
                    medicine.IsEditedDate = DateTime.UtcNow;
                    _dbcontext.Entry(medicine).State = EntityState.Modified;
                    methods.Save(_dbcontext);
                    ViewBag.Message = "Medicine Details Updated Succesfully";
                    return View();
                }
                else
                {
                   
                         ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                        ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);

                        ModelState.AddModelError("", "City is Mismatch with Branch");
                        return View();
                   
                }
            }
            ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
            ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
            return View();
        }
        //Stock List viwed by Admin
        [Authorize(Roles = "Admin")]
        public ActionResult StockList()
        {
            if (_dbcontext.Medicines.ToList().Count == 0)
            {
                ViewBag.msg = 1;
                return View();
            }
            return View(_dbcontext.Medicines.ToList());
        }
        //Editing stock list by both Branch Admin and Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult EditStock(int? id)
        {
            Medicine medicine = null;
            if (id != null)
            {
                medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();

            }

            return View(medicine);

        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult EditStock(Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                _dbcontext.Entry(medicine).State = EntityState.Modified;
                methods.Save(_dbcontext);
                ViewBag.Message = "Medicine Stock Details Updated Succesfully";
                return View();
            }
            return View();
        }

        //Branch stock list Viwed by Admin
        [Authorize(Roles = "Admin")]
        public ActionResult BranchStock()
        {

            return View(_dbcontext.Branches.ToList());
        }
        //Details of each branch Viewed by Admin based on Medicine Type
        [Authorize(Roles = "Admin")]
        public ActionResult ViewEachBranchStock(string id)
        {
            List<Medicine> stockList=new List<Medicine>();
            Branch branch = _dbcontext.Branches.FirstOrDefault(x => x.BranchId == id);
             stockList = _dbcontext.Medicines.Where(x => x.BranchAvaliable == branch.BranchName&&x.Address==branch.BranchAddress).ToList();
            var list = stockList.GroupBy(x => x.Disease).Select(Y => Y.FirstOrDefault()).ToList();
            
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        ////Details of each branch Medicine Viewed by Admin 
        public ActionResult ViewEachBranchMedicine(int id)
        {
            Medicine medicine = _dbcontext.Medicines.FirstOrDefault(x => x.MedId == id);
            var stockList = _dbcontext.Medicines.Where(x => x.Disease==medicine.Disease&&x.BranchAvaliable==medicine.BranchAvaliable&&x.Address==medicine.Address).ToList();

            return View(stockList);
        }
        //Reports Viewed by Admin
        [Authorize(Roles = "Admin")]
        public ActionResult GenenerateReport()
        {
            ViewBag.BranchList = _dbcontext.Branches.Select(x => x.BranchId);
            Branch branch = new Branch();
            return View(branch);
        }
        //Reports Viewed by Admin based on brand,stock,illness and expiry Date
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult SalesReport(Branch branch)
        {
            ViewBag.BranchId = branch.BranchId;
            return View();
        }
        //Report of Stock Viewed by both Admin and Branch Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult StocksReport(string id)
        {
            Branch branchObj = _dbcontext.Branches.FirstOrDefault(t => t.BranchId == id);
            var list = _dbcontext.Medicines.Where(t => t.BranchAvaliable == branchObj.BranchName && t.Address == branchObj.BranchAddress);
            return View(list);

        }
        //Report of Brand Viewed by both Admin and Branch Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult BrandsReport(string id)
        {
            Branch branchObj = _dbcontext.Branches.FirstOrDefault(t => t.BranchId == id);
            var list = _dbcontext.Medicines.Where(t => t.BranchAvaliable == branchObj.BranchName && t.Address == branchObj.BranchAddress);
            return View(list); 
        }
        //Report of Sales Viewed by both Admin and Branch Admin
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult SaleReport(string id)
        {
            List<OrderItem> orderItems = new List<OrderItem>();

MedicineMonitoring/MedicineMonitoring/Views/Medicine/AddMedicine.cshtml
@model MedicineMonitoring.Models.Medicine

@{ ViewBag.Title = "AddMedicine";
    Layout = null; }

@Html.Partial("_Header")

<!-- banner-section start  -->
<section class="banner-section bg_img" data-background="~/assets/images/banner.jpg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="banner-content">
                    <h1 class="title">Add Medicine Details</h1>

                    <p></p>
                </div>
            </div>
            <div class="col-md-5">

            </div>
        </div>
    </div>
</section>
<!-- banner-section end  -->
<section class="search-section pt-120 pb-120">
    <!-- banner-section end  -->
    <!-- search-section start -->

    <div class="container">
       
                        <div class="row">
                            <div class="col-lg-12">
                             
                                <div class="car-search-area">

                                    @{ if (ViewBag.Message != null)
                                        {
                            <div>

                                <h4>@ViewBag.Message</h4>
                                
                            </div> }
                        else
                        {
                            using (Html.BeginForm())
                            {
                            @Html.AntiForgeryToken()

                                                <form class="car-search-form">
                                                    <div class="row">
                                                        <div class="col-lg-4 form-group">
                                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                                            @Html.LabelFor(model => model.MedName, htmlAttributes: new { @class = "control-label col-md-6" })

                                                            @Html.EditorFor(model => model.MedName, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.MedName, "", new { @class = "text-danger" })

                                                        </div>

                                                        <div class="form-group col-lg-4">
                                                            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-6" })

                                                            @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })

                                                        </div>



                                                        <div class="col-lg-4 form-group">
                                                            @Html.LabelFor(model => model.Disease, htmlAttributes: new { @class = "control-label col-md-6" })

                                                            @Html.EditorFor(model => model.Disease, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Disease, "", new { @class = "text-danger" })

                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-4">
                                                            @Html.LabelFor(model => model.ManufactureDate, htmlAttributes: new { @class = "control-label col-md-8" })

                                                            @Html.EditorFor(model => model.ManufactureDate, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.ManufactureDate, "", new { @class = "text-danger" })

                                                        </div>



                                                        <div class="col-lg-4 form-group">
                                                            @Html.LabelFor(model => model.BranchAvaliable, htmlAttributes: new { @class = "control-label col-md-2" })

                                                            @Html.DropDownListFor(model => model.BranchAvaliable, new SelectList(ViewBag.BrachList, "BranchName"), new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.BranchAvaliable, "", new { @class = "text-danger" })

                                                        </div>

                                                        <div class="form-group col-md-4">
                                                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })

                                                            @Html.DropDownListFor(model => model.Address, new SelectList(ViewBag.BranchAddress, "Address"), new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

                                                        </div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-lg-4 form-group">
                                                            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-8" })

                                                            @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })

                                                        </div>

                                                        <div class="form-group col-md-4">
                                                            @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })

                                                            @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })

                                                        </div>

                                                        <div class="col-lg-4 form-group">
                                                            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })

                                                            @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })

                                                        </div>
                                                    </div>

                                                    <div class=" form-group col-md-8">
                                                        <button type="submit" class="cmn-btn">Submit</button>
                                                    </div>

                                                    <br>
                                                   


                                                </form> }
                                        } }
                                </div>
                            </div>
                        </div> 
    </div>
                                                    </section> <!-- search-section end -->
                        

@Html.Partial("_Footer")

MedicineMonitoring/MedicineMonitoring/Views/Medicine/BranchStockList.cshtml
@model IEnumerable<MedicineMonitoring.Models.Medicine>

@{ ViewBag.Title = "BranchStockList";
    Layout = null; }

@Html.Partial("_Header")
<!-- banner-section start  -->
<section class="banner-section bg_img" data-background="~/assets/images/banner.jpg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="banner-content">
                    <h1 class="title"> Medicine Stock List</h1>

                    <p></p>
                </div>
            </div>
            <div class="col-md-5">

            </div>
        </div>
    </div>
</section>
<!-- banner-section end  -->

<section class="search-section pt-120 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="car-search-area">


                    <form class="car-search-form">
                        <div class="row">



                            <table class="table">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MedName)
                                    </th>

                                    <th>
                                        @Html.DisplayNameFor(model => model.quantity)
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MedName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.quantity)
                        </td>
                        <td>
                           
                            <a href='@Url.Action("EditStock", "Medicine", new { id = item.MedId })' class="cmn-btn">Edit Stock</a>
                        </td>
                    </tr>}

                            </table>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section> <!-- search-section end -->

@Html.Partial("_Footer")

MedicineMonitoring/MedicineMonitoring/Views/Medicine/GenenerateReport.cshtml
@model MedicineMonitoring.Models.Branch
@{
    ViewBag.Title = "GenenerateReport";
    Layout = null;}





@Html.Partial("_Header")

<!-- banner-section start  -->
<section class="banner-section bg_img" data-background="~/assets/images/banner.jpg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-7">
                <div class="banner-content">
                    <h1 class="title">Medicine Stock Report</h1>
                    <p></p>

                </div>
            </div>

        </div>
    </div>
</section>
<!-- banner-section end  -->


@using (Html.BeginForm("SalesReport", "Medicine"))
{
    @Html.AntiForgeryToken() <!-- search-section start -->
    <section class="search-section pt-120 pb-120">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="car-search-area">
                        <center>
                            <h3 class="title">Select Branch Id</h3>
                            <form class="car-search-form">
                                <div style="align-content:center">


                                    <div class="row">
                                        <div class="form-group col-md-12">



                                            <div class="col-md-3">
                                                @Html.DropDownListFor(model => model.BranchId, new SelectList(ViewBag.BranchList, "BranchId"), new { htmlAttributes = new { @class = "form-control" } })

                                                @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class=" form-group col-md-8">
                                        <button type="submit" class="cmn-btn">Generate</button>
                                    </div>

                                </div>
                            </form>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- search-section end -->}

@Html.Partial("_Footer")

MedicineMonitoring/MedicineMonitoring/Views/Medicine/MedList.cshtml
@model IEnumerable<MedicineMonitoring.Models.Medicine>



@{ ViewBag.Title = "MedList";
    Layout = null; }

@Html.Partial("_Header")
<!-- banner-section start  -->
<section class="banner-section bg_img" data-background="~/assets/images/banner.jpg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="banner-content">
                    <h1 class="title">Medicine List</h1>
                    <p></p>

                </div>
            </div>
            <div class="col-md-5">

            </div>
        </div>
    </div>
</section>
<!-- banner-section end  -->

<section class="search-section pt-120 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="car-search-area">
                   
                        <a href='@Url.Action("AddMedicine", "Medicine")' class="btn btn-primary pull-right">Add New Medicine</a>
                    
                    <form class="car-search-form">




                        <div class="row">


                            <table class="table">
                                <tr>
                                    <th>
                                        @Html.DisplayName("Medicine Id")
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MedName)
                                    </th>

                                    <th></th>
                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MedId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MedName)
                                </td>

                                <td>
                                    <a href='@Url.Action("Edit", "Medicine", new { id = item.MedId })' class="cmn-btn">Edit Record</a>
                                    
                                </td>
                                <td>
                                    <a href='@Url.Action("Details", "Medicine", new { id = item.MedId })' class="cmn-btn">Record Details</a>
                                   
                                </td>
                            </tr>
}
                            </table>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section> <!-- search-section end -->

@Html.Partial("_Footer")

MedicineMonitoring/MedicineMonitoring/Views/Medicine/StockList.cshtml
@model IEnumerable<MedicineMonitoring.Models.Medicine>

@{ ViewBag.Title = "StockList";
    Layout = null; }

@Html.Partial("_Header")
<!-- banner-section start  -->
<section class="banner-section bg_img" data-background="~/assets/images/banner.jpg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="banner-content">
                    <h1 class="title"> Medicine Stock List</h1>
                    <p></p>
                </div>
            </div>
            <div class="col-md-5">

            </div>
        </div>
    </div>
</section>
<!-- banner-section end  -->

<section class="search-section pt-120 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="car-search-area">


                    <form class="car-search-form">
                        <div class="row">
                          


                            <table class="table">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MedName)
                                    </th>

                                    <th>
                                        @Html.DisplayNameFor(model => model.quantity)
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MedName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.quantity)
                        </td>
                        <td>
                           
                            <a href='@Url.Action("EditStock", "Medicine", new { id = item.MedId })' class="cmn-btn">Edit Stock</a>
                        </td>
                    </tr>
}

                            </table>
                        </div>
                    </form>
                   
                </div>
            </div>
        </div>
    </div>
</section> <!-- search-section end -->

@Html.Partial("_Footer")